# Generated by Django 5.1.2 on 2024-10-15 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='_profile_images')),
                ('city', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский'), ('...', '...')], default='...', max_length=7)),
                ('age', models.IntegerField(max_length=3)),
                ('contact_number', models.CharField(default='+7..........', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
